### ISSUE TITLE
potential typo in error message

### ISSUE THREAD

**Issue by nebulous** [rizen/AWS-SNS-Verify#5]
I believe the following should say 

> Could not verify the **SNS** message from its signature.

https://github.com/rizen/AWS-SNS-Verify/blob/e6752b30fdc4fc6f12f8bcfd34f6a09797a94e72/lib/AWS/SNS/Verify.pm#L92

I ended up more confused than I'd like to admit wondering how SES was involved. :)

**Comment by rizen** [comment]
fixed in 0.0105
