### ISSUE TITLE
Messages containing unicode do not validate

### ISSUE THREAD

**Issue by nebulous** [rizen/AWS-SNS-Verify#7]
Messages don't validate and rhe following error is thrown when processing messages containing unicode: `Wide character in subroutine entry at /usr/local/share/perl/5.22.1/AWS/SNS/Verify.pm line 91`
 
to reproduce, generate a message like so:
`aws sns publish --topic-arn=yourFavoriteArn --message='A Test Banana:🍌'`

observe the message string in the generated json is escaped with a unicode escape sequence: `"Message" : "A Test Banana:\uD83C\uDF4C"`

messages without said unicode escapes validate, and messages with them consistently fail to validate. Incidentally, the same test input _does_ validate with `Net::Amazon::SNS::Signature`

**Comment by rizen** [comment]
You are correct. I wrote a test to prove it. That said, I know very little about unicode, and have no need to validate it myself. If you can supply a patch then I'm happy to add it. But I cannot dedicate any time to fixing it. Looks like you found another module anyway.
